pages:
  image: openjdk
  script:
      - ls
      - javadoc ./src/* -classpath "./lib/*" -d public -quiet -Xmaxerrs 0 -Xmaxwarns 0 2>/dev/null 1>/dev/null
      - exit 0
  artifacts:
    paths:
      - public
    #- javadoc ...
# pages:
#     script:
#         — mkdir .public
#         — cp -r * .public
#         — mv .public public
#     artifacts:
#         paths:
#             [— public]
#     only:
#         [— master]