image: openjdk
pages:
  script:
    - cd ..
    - ls
    - PACKAGE="BehaviorMate"
    - mkdir public
    - javadoc --help
    - javadoc $PACKAGE $PACKAGE/src/* -classpath "$PACKAGE/lib/*" -d public -private -doctitle "$PACKAGE" || NO_CONTAINER=1
  artifacts:
    paths:
      - public